# Generated by Django 4.0.2 on 2022-02-22 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('rate', models.IntegerField()),
                ('price', models.IntegerField()),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('time', models.IntegerField()),
                ('photo', models.ImageField(upload_to='foods/')),
            ],
        ),
        migrations.DeleteModel(
            name='food',
        ),
    ]
