# Generated by Django 4.0.2 on 2022-02-22 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_foods_delete_food'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Foods',
            new_name='Food',
        ),
    ]
