# Generated by Django 4.0.2 on 2022-02-22 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_rename_foods_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='rate',
            field=models.IntegerField(default=0),
        ),
    ]
