# Generated by Django 4.0.2 on 2022-02-25 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0004_alter_food_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='type_food',
            field=models.CharField(choices=[('dinner', 'شام'), ('launch', 'ناهار'), ('drinks', 'نوشیدنی')], default='dinner', max_length=10),
        ),
    ]
